# Generated by Django 5.2.1 on 2025-05-30 01:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('carrier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('mode', models.CharField(choices=[('air', 'air'), ('sea', 'sea')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='CsvImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('PROCESSING', 'processing'), ('ERROR', 'error'), ('COMPLETED', 'completed')], default='PENDING', max_length=20)),
                ('total_rows', models.PositiveBigIntegerField(default=0)),
                ('processed_rows', models.PositiveBigIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Consolidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=3)),
                ('departure_date', models.DateField()),
                ('total_weight', models.FloatField()),
                ('total_volume', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['destination', 'departure_date'], name='shipments_c_destina_1e6058_idx')],
                'unique_together': {('destination', 'departure_date')},
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=2)),
                ('destination', models.CharField(max_length=3)),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('mode', models.CharField(choices=[('air', 'air'), ('sea', 'sea')], max_length=4)),
                ('status', models.CharField(choices=[('received', 'received'), ('in-transit', 'in-transit'), ('delivered', 'delivered')], default='received', max_length=12)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.carrier')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidationShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consolidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.consolidation')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.shipment')),
            ],
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipments_s_status_536511_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['destination', 'departure_date'], name='shipments_s_destina_947ba2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consolidationshipment',
            unique_together={('consolidation', 'shipment')},
        ),
    ]
