# Generated by Django 5.2.1 on 2025-05-30 02:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimport',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='csv_imports/'),
            preserve_default=False,
        ),
    ]
