# Generated by Django 5.2.1 on 2025-05-30 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_csvimport_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consolidation',
            options={'ordering': ['destination', 'departure_date']},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['shipment_id']},
        ),
    ]
