# Generated by Django 5.2.1 on 2025-05-31 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_alter_consolidation_options_alter_shipment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipments.customer'),
        ),
        migrations.AlterModelTable(
            name='shipment',
            table='shipments_shipment',
        ),
    ]
